name: "WorldGuardEvents"
description: Provides other plugins with valuable events concerning WorldGuard regions.
version: 1.13.2-0
api-version: 1.13
main: net.raidstone.wgevents.WorldGuardEvents
author: Weby
depend: [WorldGuard]
